#####################################################################
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: OTHER
# SPDX-FileCopyrightText: (c) 2022, OpenGateware authors and contributors
#####################################################################
custom: ["https://www.paypal.com/donate/?hosted_button_id=N7HXKEL8VJ9CN"]
